import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { type Metadata } from "next";
import { Playfair_Display, Raleway } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { Navigation } from "@/components/navigation";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  preload: false,
});

const RootLayout = ({ children }: LayoutProps<"/">) => (
  <html lang="en">
    <body
      className={`${raleway.variable} ${playfairDisplay.variable} antialiased`}
    >
      <Navigation>
        <NuqsAdapter>{children}</NuqsAdapter>
      </Navigation>
      <Analytics
        mode={
          process.env.VERCEL_ENV === "production" ? "production" : "development"
        }
      />
    </body>
  </html>
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
