import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { type Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps<"/">) => (
  <html lang="en">
    <body className="antialiased">
      <NuqsAdapter>{children}</NuqsAdapter>
      <Analytics
        mode={
          process.env.VERCEL_ENV === "production" ? "production" : "development"
        }
      />
    </body>
  </html>
);

export default RootLayout;
